[versions]
agp = "8.10.0"
com-google-devtools-ksp-gradle-plugin = "2.2.20-2.0.2"
kotlin = "2.2.20"
ksp = "2.2.20-2.0.2"
core-ktx = "1.9.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.2.1"
espresso-core = "3.6.1"
appcompat = "1.7.0"
material = "1.8.0"

activity-compose = "1.9.3"
compose-paging = "3.3.6"
compose-bom = "2024.10.01"
material3 = "1.2.0"
kakao-login = "2.20.6"
naver-oauth = "5.10.0"
hilt = "2.56.2"
coroutine = "1.6.4"
glide = "4.13.2"
navigation = "2.5.0"
navigation-hilt = "1.2.0"
safe-args = "2.5.0"
paging = "3.1.1"
retrofit = "2.9.0"
okhttp3 = "4.10.0"
okhttp3-logging = "4.9.2"
moshi = "1.15.0"
moshi-converter = "2.9.0"
ktx-activity = "1.6.1"
ktx-fragment = "1.5.0"
ktx-viewmodel = "2.5.1"
ktx-runtime = "2.5.1"
ktx-preference = "1.2.0"
constraintlayout = "2.1.4"
datastore-preferences = "1.1.1"
ted-permission = "3.3.0"
pager-indicator = "0.32.0"
coil = "3.1.0"
splash = "1.0.1"

[libraries]
com-google-devtools-ksp-gradle-plugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "com-google-devtools-ksp-gradle-plugin" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "compose-paging" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3"}
material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref="material3"}
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
navigation-hilt = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "navigation-hilt" }
pager-indicator = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "pager-indicator" }

kakao-login = { group = "com.kakao.sdk", name = "v2-all", version.ref = "kakao-login" }
naver-login = { group = "com.navercorp.nid", name = "oauth", version.ref = "naver-oauth" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
safe-args = { group = "androidx.navigation", name = "navigation-safe-args-gradle-plugin", version.ref = "safe-args"}
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-domain = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
coroutine = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutine" }
coroutine-domain = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutine" }
paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "paging"}
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
moshi-converter = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "moshi-converter" }
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
okhttp3-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3-logging" }
ted-permission = { group = "io.github.ParkSangGwon", name = "tedpermission-normal", version.ref = "ted-permission" }
ktx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "ktx-activity" }
ktx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "ktx-fragment" }
ktx-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "ktx-viewmodel" }
ktx-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "ktx-runtime" }
ktx-preference = { group = "androidx.preference", name = "preference-ktx", version.ref = "ktx-preference" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore-preferences" }
coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
splash = { group = "androidx.core", name = "core-splashscreen", version.ref = "splash" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
com-android-library = { id = "com.android.library", version.ref = "agp" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[bundles]

